# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50fc29bce55aff44a662ac4900a11cdb67085a40f263c8cef8c4c2c0b091bacd3e5d48849cee5f78215befb24ec240ac22d429a534229ef1db06c09a875e9756

test:
  secret_key_base: a367283d87681afc8ca553d09ad440166cd6140aa9411c5063f1fdb59c3b888482d9f4ae6c5e8090d8e59e8bf4ae54cf7b50fa91a9acc2e3d1aaccd166eed03c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
